name: PHP Compatibility
on:
  push

jobs:
  phpcompatibility:
    runs-on: ubuntu-latest
    name: PHP Compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: PHPCompatibility
        uses: pantheon-systems/phpcompatibility-action@7bf1b2881e207c80ad4569874ceee225f59537d1 # v1.1.1
        with:
          test-versions: 7.4-
  checkdeprecations:
    runs-on: ubuntu-latest
    name: Check for deprecations
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: 8.4
      - name: Check for deprecations
        run: |
          composer install
          composer run check-deprecations
